modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/SonarSonic/Flux-Networks/issues"

[[mods]]
modId="fluxnetworks"
version="${file.jarVersion}"
displayName="Flux Networks"
displayURL="https://curseforge.com/minecraft/mc-mods/flux-networks"
authors="Ollie Lansdell, BloCamLimb"
description='''Wireless Energy Networks'''

[[dependencies.fluxnetworks]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.15,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
