modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/SonarSonic/Flux-Networks/issues"

[[mods]]
    modId="fluxnetworks"
    version="${file.jarVersion}"
    displayName="Flux Networks"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/flux-networks"
    authors="Sonar Sonic, BloCamLimb"
    description='''Wireless Energy Networks'''

[[dependencies.fluxnetworks]]
    modId="forge"
    mandatory=true
    versionRange="[31.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
